---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin"
webhook_url: 
sections:
- type: heading
  label: General
- type: document
  path: content/data/site-settings.json
  label: Site Information
- type: directory
  path: content/global
  label: Navigation
  create: documents
  match: "**/*"
  new_doc_ext: json
  templates:
  - navigation
- type: heading
  label: Content
- type: document
  path: content/homepage.md
  label: Home
- type: directory
  path: content/pages
  label: Pages
  create: documents
  match: "**/*"
  new_doc_ext: json
  templates:
  - general-page-fields
- type: directory
  path: content/news
  label: News
  create: documents
  match: "**/*"
  new_doc_ext: json
  templates:
  - news
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: dist
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run generate
