---
label: Site Settings
hide_body: true
fields:
- name: site_title
  type: text
  config:
    required: false
  label: Site Title
  description: Main title of the website.
- name: company
  type: text
  config:
    required: false
  label: Company
  description: The name of your company
